task_experience_blog:
  description: |
    Transform the provided personal experience into a comprehensive, engaging blog post.
    
    PERSONAL EXPERIENCE TO TRANSFORM:
    {experience_text}
    
    COMPREHENSIVE WORKFLOW:
    1. ANALYSIS PHASE - Analyze the personal experience to extract:
       - Main technical topics and technologies involved
       - Key challenges faced and solutions implemented
       - Measurable outcomes and improvements achieved
       - Learning points and insights gained
       - Broader themes that would resonate with technical audiences
    
    2. RESEARCH PHASE - Use your tools to enhance the content:
       - Search for industry best practices related to mentioned technologies
       - Find relevant statistics, trends, and expert opinions
       - Look for similar case studies and success stories
       - Research advanced techniques and optimizations
       - Gather authoritative sources to support your points
    
    3. WRITING PHASE - Create the blog post with:
       - Personal narrative as the compelling foundation
       - Technical depth with specific examples and details
       - Integration of research insights and best practices
       - Practical takeaways and actionable advice
       - Professional tone balancing personal story with expertise
    
    STRUCTURE REQUIREMENTS:
    - Engaging introduction that hooks the reader with the personal story
    - Clear sections with logical flow from problem to solution
    - Technical details woven naturally into the narrative
    - Research-backed insights that enhance (don't overshadow) the personal story
    - Practical conclusions with actionable takeaways
    - Resources and references for further learning
    
    TECHNICAL DEPTH:
    - Include specific technologies, tools, and methodologies mentioned
    - Explain technical decisions and trade-offs made during the experience
    - Share measurable results and performance improvements achieved
    - Provide relevant code snippets, configurations, or examples where applicable
    - Connect personal experience to broader industry best practices
    
    AUDIENCE VALUE:
    - Address common challenges developers/engineers face in similar situations
    - Provide insights that can be applied to similar projects or scenarios
    - Balance personal vulnerability with technical authority to build trust
    - Include step-by-step reasoning without making it a basic tutorial
    - Offer resources for readers who want to dive deeper into the topics
    
    USE YOUR TOOLS EFFECTIVELY:
    - Search for current industry trends and supporting statistics
    - Scrape authoritative websites for expert insights and best practices
    - Read relevant documentation or existing knowledge to add depth
    - Research similar experiences and case studies for broader context
  
  expected_output: |
    A comprehensive, well-structured blog post (1500-2500 words) that includes:
    
    **Structure:**
    - Compelling introduction that draws readers in with the personal story
    - Clear headings and logical progression from challenge to solution
    - Multiple sections that balance narrative with technical insights
    - Strong conclusion that ties personal learning to broader implications
    
    **Content Quality:**
    - Authentic personal voice maintained throughout
    - Technical accuracy with specific examples and details
    - Research-backed insights seamlessly integrated into the narrative
    - Practical takeaways that provide real value to readers
    - Code snippets, configurations, or technical examples where relevant
    
    **Professional Elements:**
    - Engaging title that captures the essence of the experience
    - Subheadings that guide readers through the content
    - References and links to authoritative sources
    - Call-to-action or invitation for reader engagement
    - Professional formatting suitable for publication
    
    The final output should be ready for publication on technical blogs, personal websites, or professional platforms like LinkedIn or Medium.
  
  agent: writer