task_experience_blog:
  description: |
    Transform the provided personal experience into a comprehensive, engaging blog post.
    
    PERSONAL EXPERIENCE TO TRANSFORM:
    {experience_text}
    
    COMPREHENSIVE WORKFLOW:
    1. ANALYSIS PHASE - Analyze the personal experience to extract:
       - Main technical topics and technologies involved
       - Key challenges faced and solutions implemented
       - Measurable outcomes and improvements achieved
       - Learning points and insights gained
       - Broader themes that would resonate with technical audiences
    
    2. RESEARCH PHASE - Use your tools to enhance the content:
       - Search for industry best practices related to mentioned technologies
       - Find relevant statistics, trends, and expert opinions
       - Look for similar case studies and success stories
       - Research advanced techniques and optimizations
       - Gather authoritative sources to support your points
    
    3. WRITING PHASE - Create the blog post with:
       - Personal narrative as the compelling foundation
       - Technical depth with specific examples and details
       - Integration of research insights and best practices
       - Practical takeaways and actionable advice
       - Professional tone balancing personal story with expertise
    
    STRUCTURE REQUIREMENTS:
    - Engaging introduction that hooks the reader with the personal story
    - Clear sections with logical flow from problem to solution
    - Technical details woven naturally into the narrative
    - Research-backed insights that enhance (don't overshadow) the personal story
    - Practical conclusions with actionable takeaways
    - Resources and references for further learning
    
    TECHNICAL DEPTH:
    - Include specific technologies, tools, and methodologies mentioned
    - Explain technical decisions and trade-offs made during the experience
    - Share measurable results and performance improvements achieved
    - Provide relevant code snippets, configurations, or examples where applicable
    - Connect personal experience to broader industry best practices
    
    AUDIENCE VALUE:
    - Address common challenges developers/engineers face in similar situations
    - Provide insights that can be applied to similar projects or scenarios
    - Balance personal vulnerability with technical authority to build trust
    - Include step-by-step reasoning without making it a basic tutorial
    - Offer resources for readers who want to dive deeper into the topics
    
    USE YOUR TOOLS EFFECTIVELY:
    - Search for current industry trends and supporting statistics
    - Scrape authoritative websites for expert insights and best practices
    - Read relevant documentation or existing knowledge to add depth
    - Research similar experiences and case studies for broader context
  
  expected_output: |
    A comprehensive, well-structured blog post (2000-4000 words) that includes:
    
    **Structure:**
    - Compelling introduction that draws readers in with the personal story
    - Clear headings and logical progression from challenge to solution
    - Multiple sections that balance narrative with technical insights
    - Strong conclusion that ties personal learning to broader implications
    
    **Content Quality:**
    - Authentic personal voice maintained throughout
    - Technical accuracy with specific examples and details
    - Research-backed insights seamlessly integrated into the narrative
    - Practical takeaways that provide real value to readers
    - Code snippets, configurations, or technical examples where relevant
    
    **Professional Elements:**
    - Engaging title that captures the essence of the experience
    - Subheadings that guide readers through the content
    - References and links to authoritative sources
    - Call-to-action or invitation for reader engagement
    - Professional formatting suitable for publication
    
    The final output should be ready for publication on technical blogs, personal websites, or professional platforms like LinkedIn or Medium.
  
  agent: writer

rewrite_and_expand_blog_post:
  description: |
    Take the initial blog draft from the previous task and transform it into a polished, 
    long-form article suitable for LinkedIn Articles or Medium publication.
    
    REWRITING AND EXPANSION PROCESS:
    
    1. STRUCTURE ENHANCEMENT:
       - Rewrite in personal blog style (professional but approachable)
       - Add clear subheaders and improve narrative flow
       - Expand sections with deeper storytelling and explanation
       - Use short paragraphs and lists for optimal readability
    
    2. CONTENT ENRICHMENT:
       - Add researched insights and context where needed (AI trends, best practices, examples)
       - Include relevant industry statistics and expert opinions
       - Provide references to authoritative sources and best practices
       - Balance first-person storytelling with researched industry insights
       - Create smooth transitions between personal story and industry context
    
    3. DEPTH AND VALUE:
       - Expand the article to 1000-2000 words (Medium-style long read)
       - Ensure content is valuable enough that readers want to bookmark or share
       - Show both personal journey and practical lessons others can apply
       - Keep tone authentic, not overly polished or "marketing-y"
       - Avoid unnecessary jargon while maintaining technical accuracy
    
    4. PUBLICATION READINESS:
       - Create an engaging, shareable title
       - Structure with clear headers and logical progression
       - End with thoughtful conclusion and clear call for discussion
       - Include practical takeaways and actionable insights
       - Format for professional publication platforms
    
    QUALITY REQUIREMENTS:
    - Maintain authentic personal voice throughout
    - Balance vulnerability with technical authority
    - Provide real value that resonates with technical professionals
    - Create content that inspires and educates simultaneously
    - Ensure smooth reading experience with natural flow
  
  expected_output: |
    A polished, publication-ready long-form blog article (1000-2000 words) that includes:
    
    **Enhanced Structure:**
    - Compelling, shareable title
    - Professional subheadings and logical flow
    - Smooth transitions between sections
    - Engaging introduction and thoughtful conclusion
    
    **Enriched Content:**
    - Expanded personal narrative with deeper storytelling
    - Research-backed insights seamlessly integrated
    - Industry context, trends, and best practices
    - Practical takeaways and actionable advice
    - References to authoritative sources
    
    **Publication Quality:**
    - Medium/LinkedIn Articles style and formatting
    - Professional but approachable tone
    - Optimal readability with short paragraphs and lists
    - Call-to-action for reader engagement
    - Content valuable enough to bookmark and share
    
    The final article should be ready for immediate publication on professional platforms 
    and represent your authentic voice while providing significant value to technical audiences.
  
  agent: blog_writer
