task_search:
  description: |
    Research {topic} to discover compelling content angles and real-world impact stories.
    Focus on finding:
    - Recent adoption trends and success metrics
    - Common challenges developers face with {topic}
    - Business impact and productivity improvements
    - Developer experience stories (both positive and negative)
    - Industry use cases and practical applications
    - Career opportunities and skill development aspects
    
    Your goal is to identify content angles that would resonate with senior developers,
    not just technical features. Look for the "why this matters" and "how this changes things" stories.
    
    Your final answer MUST be a curated list of 5-7 compelling content angles about {topic}
    that focus on developer experience, business impact, and career relevance.
  expected_output: |
    A curated list of 5-7 compelling content angles about {topic}, each with:
    - The angle/story approach (e.g., "How {topic} changed our deployment process")
    - Key supporting data or trends that make this angle relevant
    - Target audience appeal (why senior developers would care)
    - Potential personal experience hooks for the writer
  agent: coach

task_research:
  description: |
    CONTENT ANGLE SELECTION: Choose the MOST compelling content angle from the coach's research
    about {topic}. Select based on:
    - Relevance to senior .NET Developer and DevOps engineer experience
    - Availability of supporting data and real-world examples
    - Potential for personal, experience-driven storytelling
    - Career and business impact potential
    
    TARGETED RESEARCH PHASE: Use your search_tool to gather supporting evidence for this angle:
    - Real-world implementation examples and case studies
    - Developer productivity metrics and business impact data
    - Common challenges and how teams overcome them
    - Before/after scenarios and transformation stories
    - Industry adoption trends and future projections
    - Expert opinions and developer community feedback
    - Specific tools, workflows, and best practices
    
    STORYTELLING SUPPORT: Find narrative elements that support personal experience storytelling:
    - Team transformation stories
    - Learning curve experiences
    - Problem-solution scenarios
    - "Aha moments" and breakthrough insights
    
    Base ALL findings on REAL DATA with proper source attribution.
  expected_output: |
    A comprehensive research package for ONE compelling content angle about {topic}, including:
    - The chosen content angle and why it was selected
    - Supporting data, statistics, and real-world examples
    - Narrative elements for personal experience storytelling
    - Quotes, case studies, and expert insights
    - Sources and attribution for all claims
  agent: researcher
  context:
    - task_search

task_blog:
  description: |
    Using the research findings as your foundation, write a reflective blog post about the 
    specific {topic} skill that was researched. Make it personal by drawing on your own 
    experience as a senior developer and DevOps engineer. The blog should balance insight 
    with practicality: not just hype, but real examples of where this technology makes an impact. 
    
    Use the research data, statistics, case studies, and market trends to support your points.
    Structure the post with a clear, professional headline (no strict character limit), 
    an introduction, body, and conclusion. Keep the tone reflective and thoughtful, while 
    still being accessible and engaging for a professional audience.
  expected_output: |
    - A blog post between 1200 and 2000 words
    - A clear, professional headline (no strict character limit)
    - A reflective and personal tone, grounded in research data and real-world experience
    - Concrete examples, statistics, and insights from the research
    - Well-structured with intro, body, and conclusion
    - Focused on thought leadership backed by data
  agent: writer
  context:
    - task_research

task_post:
  description: |
    Write a short, engaging LinkedIn post (almost one-liner style) to promote
    a blog post about {topic}. The post should be concise, professional,
    and spark curiosity without giving everything away. It should encourage
    readers to click the blog link for the full story. The style should be
    direct, pragmatic, and slightly personal, reflecting the voice of a senior
    .NET Developer and DevOps engineer.
  expected_output: |
    - A LinkedIn promo post under 75 words
    - Clear, engaging, and professional tone
    - Includes a placeholder for the blog link
    - Optional 1–3 relevant hashtags (keep it minimal and professional)
    - Written in an almost one-liner style
  agent: influencer
  context:
    - task_blog