task_search:
  description: |
    Make a detailed report on the latest rising skills in {topic} space. 
    Your final answer MUST be a list of at least 5 exciting new {topic} skills
    in the format of bullet points.
  expected_output: |
    A comprehensive list of at least 5 exciting new {topic} skills with brief explanations 
    of why they are trending and in demand, formatted as bullet points.
  agent: coach

task_research:
  description: |
    IMPORTANT: You MUST select EXACTLY ONE skill from the coach's research list about {topic} skills.
    Pick the one that you find most interesting or promising for a deep dive related to a senior .NET Developer and DevOps engineer.
    
    COMPREHENSIVE RESEARCH PHASE: Use your search_tool to conduct in-depth research on this ONE chosen skill:
    - Search for recent trends, statistics, and market demand data
    - Find real job postings, salary ranges, and employment growth projections
    - Research current industry examples, case studies, and success stories
    - Look for expert opinions, predictions, and future outlook
    - Find specific tools, technologies, and certifications related to this skill
    - Research career paths and progression opportunities
    - Search for challenges and opportunities in this field
    
    ARTICLE CREATION: Write a comprehensive, well-researched article (1000-1500 words) about this ONE skill.
    Structure your article with:
    1. Introduction to the skill and its importance
    2. Current market demand and statistics
    3. Real-world applications and case studies
    4. Career opportunities
    6. Future outlook and predictions
    
    Base ALL content on REAL DATA from your search results with proper source attribution.
  expected_output: |
    A comprehensive, well-researched article (1000-1500 words) about EXACTLY ONE {topic} skill.
  agent: researcher

task_post:
  description: |
    Write a reflective LinkedIn post about {topic}, making it personal by drawing
    on your own experience as a senior .NET Developer and DevOps engineer. The post
    should balance insight with practicality: not just hype, but real examples of
    where AI and technology make an impact. Structure the post with a clear
    headline (30 characters max), conversational yet professional tone, and
    short, readable paragraphs. Include your perspective on both the opportunities
    and the limitations of {topic}.
  expected_output: |
    - A LinkedIn post under 500 words
    - A headline under 30 characters
    - Clear, professional, and personal tone
    - Concrete examples or insights from experience
    - Reflective and thought-leadership style
    - Includes relevant hashtags (1–4, not overdone)
  agent: influencer