task_search:
  description: |
    Make a detailed report on the latest rising skills in {topic} space. 
    Your final answer MUST be a list of at least 5 exciting new {topic} skills
    in the format of bullet points.
  expected_output: |
    A comprehensive list of at least 10 exciting new {topic} skills with brief explanations 
    of why they are trending and in demand, formatted as bullet points.
  agent: coach

task_research:
  description: |
    IMPORTANT: You MUST select EXACTLY ONE skill from the coach's research list about {topic} skills.
    Pick the one that you find most interesting or promising for a deep dive related to a senior .NET Developer and DevOps engineer.
    Try to avoid political topics or topics about ethics, diversity, or social issues.
    
    COMPREHENSIVE RESEARCH PHASE: Use your search_tool to conduct in-depth research on this ONE chosen skill:
    - Search for recent trends, statistics, and market demand data
    - Find real job postings, salary ranges, and employment growth projections
    - Research current industry examples, case studies, and success stories
    - Look for expert opinions, predictions, and future outlook
    - Find specific tools, technologies, and certifications related to this skill
    - Research career paths and progression opportunities
    - Search for challenges and opportunities in this field
    
    RESEARCH OUTPUT: Compile all your research findings into a comprehensive research document.
    Include all data, statistics, sources, and insights you've gathered.
    
    Base ALL content on REAL DATA from your search results with proper source attribution.
  expected_output: |
    A comprehensive research document with all findings, data, statistics, case studies, 
    and sources about EXACTLY ONE {topic} skill.
  agent: researcher
  context:
    - task_search

task_blog:
  description: |
    Write a reflective and professional blog post about {topic}, grounded in real-world
    experience as a developer. You can gather additional information using your search tool if needed.

    STRUCTURE:
    - Open with a clear personal hook (a challenge, incident, or insight that makes the story real).
    - Move into technical exploration: what tools, frameworks, or approaches were tried.
    - Share lessons learned: what worked, what didn’t, and the trade-offs made.
    - Provide actionable recommendations for readers.
    - End with a forward-looking conclusion (inspiration, next steps, or reflections).

    TECHNICAL DEPTH:
    - Mention specific tools, frameworks, and integrations (with versions where relevant).
    - Include technical details where they add value (snippets, CLI commands, configs).
    - Share measurable improvements (metrics, benchmarks, before/after results).
    - Discuss architecture decisions or trade-offs where applicable.

    TONE AND STYLE:
    - Professional, reflective, and approachable (thought-leadership voice).
    - Personal but not overly casual — insights backed by experience.
    - Honest about limitations, failures, and what was learned.
    - Balanced: human story + technical expertise.

    VALUE FOR AUDIENCE:
    - Address real challenges your audience of developers, engineers, and tech leads face.
    - Provide actionable insights they can take away immediately.
    - Make complex concepts accessible without oversimplifying.
    - Inspire confidence and curiosity: readers should feel "I learned something useful here."

  expected_output: |
    - A blog post between 800 and 1500 words
    - An engaging, professional headline (not clickbait, but curiosity-driven)
    - Clear structure (intro, body, conclusion with lessons learned)
    - Personal story as hook, but majority focused on insights and value
    - Specific technical details/examples (not a full tutorial, but enough to show credibility)
    - Reflective tone with practical takeaways
    - Conclusion that gives clear recommendations or next steps
  agent: writer
  context:
    - task_research

task_post:
  description: |
    Write a punchy LinkedIn post that makes people STOP scrolling and lean in.
    You're not just promoting a blog—you’re sharing a real developer insight in a way
    that sparks curiosity and conversation.
    
    HOOK FIRST:
    - Open with a relatable pain point, strong question, or surprising moment
    - Make it feel human and specific ("2 AM. Production down. Nobody remembered why...")

    STORY + VALUE:
    - Give a quick glimpse of the challenge and the insight that changed everything
    - Hint at the bigger story or solution (but don’t give it all away)
    - Use plain, conversational language—like talking to a colleague over coffee
    - Add personality (frustration, relief, humor, or excitement) to make it memorable
    
    CALL TO ACTION:
    - Make readers feel curious and that they’ll miss out if they don’t click
    - Keep it authentic, not salesy
    
    LINKEDIN CONTEXT:
    - Posts should be short and scannable (50–100 words max)
    - Use line breaks for rhythm and readability
    - Add 2–4 hashtags that reach the right dev/tech audience
    - Tone: confident but humble, like an experienced dev sharing a lesson learned
    
    GOAL:
    - Create a moment where readers think: "That’s me." + "I need to know more."
    - Drive clicks to the blog while starting conversations in the comments.
  expected_output: |
    - A LinkedIn post of 50–100 words
    - Strong hook in the first line (relatable problem, question, or dramatic moment)
    - Tease of the most valuable blog insight, without full detail
    - Conversational tone, authentic voice, and human emotion
    - Smooth call-to-action that invites reading the blog
    - 2–4 strategic hashtags
    - Short, scannable structure with line breaks
  agent: influencer
  context:
    - task_blog