task_search:
  description: |
    Make a detailed report on the latest rising skills in space of {topic}. 
    Your final answer MUST be a list of at least 5 exciting new skills
    in the format of bullet points.
  expected_output: |
    A comprehensive list of at least 5 exciting new skills with brief explanations 
    of why they are trending and in demand, formatted as bullet points.
  agent: coach

task_post:
  description: |
    Write a LinkedIn post with a short but impactful headline. 
    It should list the latest skills in {topic} which are going to be in demand.
  expected_output: |
    An engaging LinkedIn post with a compelling headline (max 30 characters) and content 
    that lists trending skills in {topic} with relevant emojis and hashtags.
  agent: influencer

task_critique:
  description: |
    Identify parts of the post that aren't written concise enough and improve them. 
    Make sure that the post has engaging headline with 30 characters max.
  expected_output: |
    A refined and improved LinkedIn post that is concise, professional and engaging.
    Has an impactful headline under 30 characters, includes relevant emojis and hashtags.
  agent: critic