task_search:
  description: |
    Make a detailed report on the latest items featuring the the topic '{topic}'. 
    Your final answer MUST be a list of at least 10 exciting items about the topic '{topic}'
    in the format of bullet points.
  expected_output: |
    A comprehensive list of at least 10 exciting new items about the topic '{topic}' with brief explanations
    of why they are trending and in demand, formatted as bullet points.
  agent: coach

task_research:
  description: |
    Write a comprehensive research article about the topic '{topic}'.

    You are a technical writer. Your job is to create content about the topic '{topic}', not demonstrate tools.

    CONTENT REQUIREMENTS:
    - Write 800+ words of actual research content about the topic '{topic}'
    - Include technical details, examples, and best practices
    - Structure: Introduction, main content sections, conclusion
    - Use search_tool ONLY if you need specific information - do not demonstrate tool usage

    IMPORTANT: Output the research article directly. Do not show tool code, tool usage examples, or instructions about tools.
  expected_output: |
    A complete research article about the topic '{topic}' with technical depth and practical insights.
    No tool demonstrations or code examples - just the actual research content.
  agent: researcher
  context:
    - task_search

task_blog:
  description: |
    Write a reflective and professional blog post about the topic '{topic}', grounded in real-world
    experience as a senior .NET Developer and DevOps engineer.
    Use the research document from task_research as your primary source of information 
    but feel free to get more information with provided tools if needed.

    STRUCTURE:
    - Open with a clear personal hook (a challenge, incident, or insight that makes the story real).
    - Move into technical exploration: what tools, frameworks, or approaches were tried.
    - Share lessons learned: what worked, what didn’t, and the trade-offs made.
    - Provide actionable recommendations for readers.
    - End with a forward-looking conclusion (inspiration, next steps, or reflections).

    TECHNICAL DEPTH:
    - Mention specific tools, frameworks, and integrations (with versions where relevant).
    - Include technical details where they add value (snippets, CLI commands, configs).
    - Share measurable improvements (metrics, benchmarks, before/after results).
    - Discuss architecture decisions or trade-offs where applicable.

    TONE AND STYLE:
    - Professional, reflective, and approachable (thought-leadership voice).
    - Personal but not overly casual — insights backed by experience.
    - Honest about limitations, failures, and what was learned.
    - Balanced: human story + technical expertise.

    VALUE FOR AUDIENCE:
    - Address real challenges your audience of developers, engineers, and tech leads face.
    - Provide actionable insights they can take away immediately.
    - Make complex concepts accessible without oversimplifying.
    - Inspire confidence and curiosity: readers should feel "I learned something useful here."

    DONT'S:
    - Don’t make it a tutorial or step-by-step guide.
    - Don't mention yourself as a senior .NET developer and DevOps engineer

  expected_output: |
    - A blog post between 800 and 1500 words
    - An engaging, professional headline (not clickbait, but curiosity-driven)
    - Clear structure (intro, body, conclusion with lessons learned)
    - Personal story as hook, but majority focused on insights and value
    - Specific technical details/examples (not a full tutorial, but enough to show credibility)
    - Reflective tone with practical takeaways
    - Conclusion that gives clear recommendations or next steps
  agent: writer
  context:
    - task_research

task_post:
  description: |
    Write a punchy LinkedIn post that makes people STOP scrolling and lean in.
    You're not just promoting a blog—you’re sharing a real developer insight in a way
    that sparks curiosity and conversation.
    
    HOOK FIRST:
    - Open with a relatable pain point, strong question, or surprising moment
    - Make it feel human and specific ("2 AM. Production down. Nobody remembered why...")

    STORY + VALUE:
    - Give a quick glimpse of the challenge and the insight that changed everything
    - Hint at the bigger story or solution (but don’t give it all away)
    - Use plain, conversational language—like talking to a colleague over coffee
    - Add personality (frustration, relief, humor, or excitement) to make it memorable
    
    CALL TO ACTION:
    - Transition naturally: "Here’s what I learned..." / "The full story’s here ↓"
    - Make readers feel curious and that they’ll miss out if they don’t click
    - Keep it authentic, not salesy
    
    LINKEDIN CONTEXT:
    - Posts should be short and scannable (50–100 words max)
    - Use line breaks for rhythm and readability
    - Add 2–4 hashtags that reach the right dev/tech audience
    - Tone: confident but humble, like an experienced dev sharing a lesson learned
    
    GOAL:
    - Create a moment where readers think: "That’s me." + "I need to know more."
    - Drive clicks to the blog while starting conversations in the comments.

    IMPORTANT: Output the complete LinkedIn post directly. Do not show tool code, tool usage, or instructions about tools.
  expected_output: |
    - A LinkedIn post of 50–100 words
    - Strong hook in the first line (relatable problem, question, or dramatic moment)
    - Tease of the most valuable blog insight, without full detail
    - Conversational tone, authentic voice, and human emotion
    - Smooth call-to-action that invites reading the blog
    - 2–4 strategic hashtags (#DevOps #AItools #GitHub #Productivity)
    - Short, scannable structure with line breaks
  agent: influencer
  context:
    - task_blog
